language: cpp
compliler: gcc

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script:
  - rm -rf build
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test